# System settings file 
title = "CLI Chat Client"


[globals]
terminal = true  # Set this to false if running as graphical app


[auth]
api_key = "your_key_here"


[bot]
url = "https://api.x.ai/v1/chat/completions"
model = "grok-3-mini-latest"
stream = false
temperature = 0.7
reasoning_effort = "high"
speak_color = "cyan"


